/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns 200 with a static payload.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's id and email.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livekit/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Livekit Token
         * @description Mint a LiveKit access token for the authenticated user.
         *
         *     The route is a thin adapter over :func:`core.livekit.issue_token`;
         *     the token's `identity` is the Supabase user id and the room
         *     defaults to ``user-{userId}`` when the client does not specify one.
         */
        post: operations["livekit_token_livekit_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Preferences
         * @description Return every stored preference for the authenticated user.
         *
         *     Thin adapter over :func:`core.preferences.list`. The user's bearer
         *     token is forwarded to the Supabase client so RLS policies (defined
         *     in ``0001_user_preferences.sql``) apply to the database query.
         */
        get: operations["list_preferences_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Memories
         * @description Return the authenticated user's recent episodic memories.
         *
         *     Thin adapter over :func:`core.memory.list_recent`. The user's
         *     bearer token is forwarded for symmetry with the preferences route;
         *     mem0 itself does not consume the Supabase JWT today (it talks to
         *     Postgres directly), but RLS policies on ``mem0_memories`` enforce
         *     user isolation at the database level — see ``0003_mem0_memories.sql``.
         */
        get: operations["list_recent_memories_memories_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Return the authenticated user's conversations, paginated.
         *
         *     Thin adapter over :func:`core.conversations.list_for_user`. RLS
         *     enforces user scoping at the database; the route just shapes the
         *     response. ``limit`` is bounded server-side so a hostile client
         *     cannot ask for the whole table.
         */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Return one conversation with its full message log.
         *
         *     Returns 404 when the conversation does not exist *or* belongs to
         *     another user. Both surface here as ``None`` from the core layer
         *     because RLS makes "not yours" indistinguishable from "not there"
         *     — leaking the difference would itself be a privacy bug.
         */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConversationDetailResponse
         * @description Response payload for ``GET /conversations/{id}``.
         */
        ConversationDetailResponse: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Summary */
            summary?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Messages */
            messages?: components["schemas"]["MessageItem"][];
        };
        /**
         * ConversationSummaryItem
         * @description One row in the history list view.
         *
         *     Mirrors :class:`core.conversations.ConversationSummary`. We project
         *     explicitly through pydantic instead of returning the dataclass so
         *     the OpenAPI schema (and thus the generated TypeScript types) carry
         *     field-level descriptions.
         */
        ConversationSummaryItem: {
            /**
             * Id
             * @description Conversation UUID.
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             * @description When the conversation began.
             */
            started_at: string;
            /**
             * Ended At
             * @description When the conversation ended, or null if still in progress.
             */
            ended_at?: string | null;
            /**
             * Summary
             * @description LLM-generated one-line gist; null until the conversation ends.
             */
            summary?: string | null;
            /**
             * Message Count
             * @description Number of messages in the conversation.
             */
            message_count: number;
        };
        /**
         * ConversationsListResponse
         * @description Paginated response for ``GET /conversations``.
         */
        ConversationsListResponse: {
            /**
             * Conversations
             * @description Conversations ordered by started_at descending.
             */
            conversations?: components["schemas"]["ConversationSummaryItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe payload.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * LivekitTokenRequest
         * @description Optional body for `/livekit/token`.
         *
         *     The room is optional — when omitted, the API picks the per-user
         *     default (``user-{userId}``). Letting the client name a room is
         *     useful for tests and for future multi-room features but is not
         *     required by the demo.
         */
        LivekitTokenRequest: {
            /**
             * Room
             * @description Optional LiveKit room name; defaults to `user-{userId}`.
             */
            room?: string | null;
        };
        /**
         * LivekitTokenResponse
         * @description Connection bundle returned to the browser.
         */
        LivekitTokenResponse: {
            /**
             * Token
             * @description Short-lived LiveKit access JWT.
             */
            token: string;
            /**
             * Url
             * @description LiveKit server URL the browser should dial.
             */
            url: string;
            /**
             * Room
             * @description Room name encoded in the token's grants.
             */
            room: string;
        };
        /**
         * MeResponse
         * @description Authenticated user, projected for the wire.
         */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /**
         * MemoriesResponse
         * @description Response payload for ``GET /memories/recent``.
         */
        MemoriesResponse: {
            /**
             * Memories
             * @description The authenticated user's most recent memories, newest-first by mem0's ordering.
             */
            memories?: components["schemas"]["MemoryItem"][];
        };
        /**
         * MemoryItem
         * @description One recalled memory, projected for the wire.
         *
         *     Mirrors :class:`core.memory.Memory`. We expose ``id`` so a future
         *     UI can attribute updates back to the same memory; ``score`` is
         *     intentionally omitted from the listing endpoint because the
         *     sidebar lists rather than ranks.
         */
        MemoryItem: {
            /**
             * Id
             * @description Stable identifier mem0 assigns to the memory.
             */
            id: string;
            /**
             * Content
             * @description The remembered fact, in natural language.
             */
            content: string;
        };
        /**
         * MessageItem
         * @description A single transcript turn for the detail view.
         */
        MessageItem: {
            /** Id */
            id: string;
            /**
             * Role
             * @description One of 'user', 'assistant', 'tool'.
             */
            role: string;
            /** Content */
            content: string;
            /** Tool Name */
            tool_name?: string | null;
            /** Tool Args */
            tool_args?: {
                [key: string]: unknown;
            } | null;
            /** Tool Result */
            tool_result?: unknown | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PreferencesResponse
         * @description Flat key-value map of the authenticated user's preferences.
         *
         *     The shape is intentionally a single ``preferences`` field rather
         *     than the response body itself being a free-form object — FastAPI
         *     + OpenAPI handle nested objects more reliably than top-level
         *     ``additionalProperties`` schemas, and the frontend reads
         *     ``response.preferences`` either way.
         */
        PreferencesResponse: {
            /**
             * Preferences
             * @description All stored preferences for the authenticated user.
             */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    livekit_token_livekit_token_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LivekitTokenRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivekitTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_memories_memories_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Conversation UUID. */
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
